spring.application.name=ms-reportes

server.port=8090

# Base de datos prueba7
spring.datasource.url=jdbc:mysql://localhost:3306/prueba7?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Liquibase obligado por rúbrica
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.clear-checksums=true
# Logs requeridos
logging.level.com.ecommerce.msreportes=INFO