spring.application.name=ms-empleados
server.port=8089

# Base de datos prueba6
spring.datasource.url=jdbc:mysql://localhost:3306/prueba6?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Liquibase (Obligatorio por rúbrica)
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.parameters.clear-checksums=true
spring.liquibase.clear-checksums=true

# Trazas de Logs
logging.level.com.ecommerce.msempleados=INFO