spring:
  application:
    name: ms-envios

  datasource:
    url: jdbc:mysql://localhost:3306/prueba5?createDatabaseIfNotExist=true
    username: root
    password: "" # Al estar vacía, se define como un String vacío explícito

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    parameters:
      clear-checksums: true
    clear-checksums: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true


logging:
  level:
    com:
      ecommerce:
        msenvios: INFO