spring.application.name=ms-envios
server.port=8086

# Base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/prueba5?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.parameters.clear-checksums=true
spring.liquibase.clear-checksums=true
# Logs requeridos
logging.level.com.ecommerce.msenvios=INFO