spring.application.name=ms-usuario
server.port=8081

# Configuración de MySQL Local (Workbench)
spring.datasource.url=jdbc:mysql://localhost:3306/prueba1?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
# ¡OJO! Aquí pon la contraseña que usas para entrar a MySQL Workbench
spring.datasource.password=1234
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Dialecto actualizado para MySQL 8 o superior
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Logs
logging.level.com.prueba.ms_usuario=INFO
spring.cloud.compatibility-verifier.enabled=false