spring.application.name=ms-usuario
# Puerto
server.port=8081

# BD en memoria (Se borra al cerrar, se crea al abrir)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# Esto hace que Spring cree las tablas solo
spring.jpa.hibernate.ddl-auto=update